### ISSUE TITLE
Deploiement sur heroku

### ISSUE THREAD

**Issue by ly-abdourahamane** [M2DL/2019-ivvq-studentscollab#18]
Bonjour,

Nous n'arrivons toujours pas à déployé sur heroku.

Nous avons une erreur sur la gestion de la mémoire.

@M2DL/enseignants-ivvq
@erikmd

**Comment by erikmd** [comment]
Bonjour Abdourahamane, je n'ai pas encore eu le temps de regarder le problème que vous soulevez... mais je vais m'en occuper avant la séance de TPne de vendredi. En attendant que le déploiement continu soit opérationnel, vous pouvez vous concentrer sur les autres aspects du projet... (tests, etc.)

**Comment by ly-abdourahamane** [comment]
Bonjour Monsieur Martin-Dorel (@M2DL/enseignants-ivvq),

Nous avons réussi à regler le problème grace à l'aide de notre collègue Olivier. 
Le deploiement est fait et tout fonctionne.

Cordialement,
L'équipe studentsCollab
